### ISSUE TITLE
Compile problems

### ISSUE THREAD

**Issue by spags22** [riparino/Task_Scheduler_ALPC#1]
After adding #pragma warning(disable : 4995) to the ALPC-TaskSched-LPE.cpp file to address compiler C4995 errors, I am getting a linker error. Microsoft states the StartXpsPrintJob() function is deprecated. Am I missing a library?

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol StartXpsPrintJob referenced in function "int __cdecl mainf(void)" (?mainf@@YAHXZ)	ALPC-TaskSched-LPE	C:\Users\....\ALPC-TaskSched-LPE\ALPC-TaskSched-LPE.obj	1

**Comment by riparino** [comment]
Hey spags22, I'm looking into this. I can't seem to get it to reproduce. Which Windows are you testing on?

**Comment by spags22** [comment]
Windows 10. I had to add these statements to the top of the ALPC-TaskSched-LPE.cpp file:

#pragma comment(lib, "XpsPrint.lib")
#pragma warning(disable : 4995)
